export enum ModelType {
  SUPER_ADMINISTRATOR = 'SUPER ADMINISTRADOR',
  ADMINISTRATOR = 'ADMINISTRADOR',
  CUSTOMER = 'CLIENTE',
  MECHANIC = 'MECÁNICO',
}

export const StatusTypeList = [
  ModelType.SUPER_ADMINISTRATOR,
  ModelType.ADMINISTRATOR,
  ModelType.CUSTOMER,
  ModelType.MECHANIC,
];
