export enum EntityFromSystemType {
  APPOINTMENTS = 'AGENDAMIENTO',
  AUTH = 'AUTENTICACIÓN',
  BRANDS = 'BRANDS',
  CORE = 'NÚCLEO',
  ENTITY_FROM_SYSTEM = 'ENTIDADES DEL SISTEMA',
  MODELS = 'MODELS',
  FUELS = 'FUELS',
  PERMISSIONS = 'PERMISOS',
  PRODUCTS = 'PRODUCTOS',
  ROLES = 'ROLES',
  USERS = 'USUARIOS',
  VEHICLES = 'VEHÍCULOS',
}
